### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-scrapers-baseball-stats#10]
This issue depends on #9 

Once search is working for players, add the ability for ["fuzzy search", also known as "approximate string matching"](http://en.wikipedia.org/wiki/Approximate_string_matching). For example if I couldn't remember a player's full first and last name, but I remembered that his first name began with "Han" and his last name began with "Ram", I could search "Han Ram" and be presented with the player "Hanley Ramirez". Or, if I forgot how to spell his name and typed "Hanly Ramirez" I should still be presented with the result for "Hanley Ramirez". 

There should be some [Solr](https://lucene.apache.org/solr/) library functions available to help achieve this.

Estimated 250 pts

**Comment by EasterAndJay** [comment]
Approved 150pts

**Comment by EasterAndJay** [comment]
Closed
