### ISSUE TITLE
View a player's stats

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-scrapers-baseball-stats#7]
When viewing the whole table of data, implement the ability to select a player and open a new window with detailed statistics for that player. The exact user interaction which will cause the opening of the new window is left up to the developer. 

One option might be to double click on a player's name to cause the opening of a new window. Another option might be to add additional buttons next to the table, and when a player's name is selected, the user can click a button to "Show Player Stats" which causes the opening of the new window. 

Estimated 300 pts

**Comment by EasterAndJay** [comment]
Approved 300 pts

**Comment by EasterAndJay** [comment]
Closed
