### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-scrapers-baseball-stats#9]
Add the appropriate Java Swing elements to create a "search box" where you can enter the name of a player for which you would like to view statistics. This would be used to filter the data. For example, typing "Tony Gwynn" would result in just the one row of statistics for that player. Alternatively, typing "Gonzalez" should result in the statistics for any player with "Gonzalez" in his name. This means that the search should look at both first and last names. If there are no results found for a given search, then display an appropriate message to the user. 

The [Apache Solr](http://lucene.apache.org/solr/) library may be helpful for this. [Here is a simple tutorial](http://lucene.apache.org/solr/4_0_0/tutorial.html).

**Comment by EasterAndJay** [comment]
Approximately ~150pts

**Comment by EasterAndJay** [comment]
Closed
